spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookster
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: root
    password: root
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
          trust: "*"
        starttls:
          enabled: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads